Feature: Run client generation with multiple OpenAPI specs
golemcloud/golem-openapi-client-generator pull request #7
Opened 2024-02-22 15:59 UTC by nicoburniske

2024-02-22 17:19 UTC, senia-psm requested changes

2024-02-22 17:19 UTC, senia-psm commented on src/merger.rs
> +                println!("Entry is already occupied {:?}", entry.key());
Any merge conflict should just fail merge. We have to compare values. If they are not the same - just fail the merge.

2024-02-22 17:23 UTC, senia-psm approved these changes

2024-02-27 18:08 UTC, justcoon approved these changes

2024-02-29 15:51 UTC, merged